curations:
  packages:
  - id: "PyPI::pytest-cov:4.0.0"
    curations:
      comment: "Add correct license"
      concluded_license: MIT
  - id: "PyPI::coverage:6.5.0"
    curations:
      comment: "Add correct license"
      concluded_license: Apache-2.0
  - id: "PyPI::grpcio:1.49.1"
    curations:
      comment: "Add correct license"
      concluded_license: Apache-2.0
  - id: "PyPI::identify:2.5.6"
    curations:
      comment: "Add correct license"
      concluded_license: MIT
  - id: "PyPI::setuptools:65.5.0"
    curations:
      comment: "Add correct license"
      concluded_license: MIT