# Copyright (c) 2022 Robert Bosch GmbH and Microsoft Corporation
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0

---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: >
          (?x)^(
              .*_pb2.py|
              .*_pb2.pyi|
              .*_pb2_grpc.py
          )$
      - id: end-of-file-fixer
        exclude: >
          (?x)^(
              .*_pb2.py|
              .*_pb2.pyi|
              .*_pb2_grpc.py
          )$
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        exclude: >
          (?x)^(
              .*_pb2.py|
              .*_pb2.pyi|
              .*_pb2_grpc.py|
              .*.log
          )$
      - id: check-merge-conflict

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: >
          (?x)^(
              .*_pb2.py|
              .*_pb2.pyi|
              .*_pb2_grpc.py|
              examples/.*|
              .project-creation/.skeleton/.*
          )$

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        exclude: >
          (?x)^(
              .*_pb2.py|
              .*_pb2.pyi|
              .*_pb2_grpc.py|
              examples/.*
          )$

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        exclude: >
          (?x)^(
              .*_pb2.py|
              .*_pb2.pyi|
              .*_pb2_grpc.py
          )$
        additional_dependencies:
          - flake8-bugbear
          - flake8-unused-arguments

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["--skip=B101"]
        types_or: [python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        exclude: >
          (?x)^(
              .*_pb2.py|
              .*_pb2.pyi|
              .*_pb2_grpc.py
          )$
        args: [.]
        language: system
        pass_filenames: false

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        exclude: >
          (?x)^(
              .*_pb2.py|
              .*_pb2.pyi|
              .*_pb2_grpc.py
          )$

  # - repo: https://github.com/Lucas-C/pre-commit-hooks
  #   rev: v1.3.1
  #   hooks:
  #     - id: insert-license
  #       files: '.*\.(py|pyi|yaml|yml|sh|helmignore|dockerignore|gitignore)$'
  #       args:
  #         - --license-filepath
  #         - license_header.txt
  #         - --comment-style
  #         - "#"
  #     - id: insert-license
  #       files: '.*\.(proto)$'
  #       args:
  #         - --license-filepath
  #         - license_header.txt
  #         - --comment-style
  #         - //
  #     - id: insert-license
  #       files: "Dockerfile.*"
  #       args:
  #         - --license-filepath
  #         - license_header.txt
  #         - --comment-style
  #         - "#"
