proto < ./../sdv/proto/sdv/databroker/v1/collector.proto
@port=55555
@host=localhost:{{port}}/sdv.databroker.v1.Collector

GRPC /RegisterDatapoints
{
    "list": [
        {
            "name": "Vehicle.Speed",
            "value_type": 8,
            "description": "The speed of the vehicle",
            "change_type": 2
        }
    ]
}
