"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import chariott.common.v1.common_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _RegistrationState:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _RegistrationStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RegistrationState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    REGISTRATION_STATE_ANNOUNCED: _RegistrationState.ValueType  # 0
    """service is not registered for Chariott, upon this result the service should call the `Register` method."""

    REGISTRATION_STATE_NOT_CHANGED: _RegistrationState.ValueType  # 1
    """service is registered and successfully announced to Chariott."""

class RegistrationState(_RegistrationState, metaclass=_RegistrationStateEnumTypeWrapper):
    pass

REGISTRATION_STATE_ANNOUNCED: RegistrationState.ValueType  # 0
"""service is not registered for Chariott, upon this result the service should call the `Register` method."""

REGISTRATION_STATE_NOT_CHANGED: RegistrationState.ValueType  # 1
"""service is registered and successfully announced to Chariott."""

global___RegistrationState = RegistrationState


class IntentServiceRegistration(google.protobuf.message.Message):
    """*
    This is used as input to the `Announce` and `Register` method.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _ExecutionLocality:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _ExecutionLocalityEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[IntentServiceRegistration._ExecutionLocality.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        EXECUTION_LOCALITY_LOCAL: IntentServiceRegistration._ExecutionLocality.ValueType  # 0
        EXECUTION_LOCALITY_CLOUD: IntentServiceRegistration._ExecutionLocality.ValueType  # 1
    class ExecutionLocality(_ExecutionLocality, metaclass=_ExecutionLocalityEnumTypeWrapper):
        """*
        A side note about the `ExecutionLocality`. When `CLOUD` is selected this doesn't
        mean that the service will be invoked directly in the cloud through Chariott,
        but that the service will be invoked in the cloud through a local installed provider
        that acts as a proxy to the cloud service. This allows abstraction of the cloud
        service interface and protocol.
        """
        pass

    EXECUTION_LOCALITY_LOCAL: IntentServiceRegistration.ExecutionLocality.ValueType  # 0
    EXECUTION_LOCALITY_CLOUD: IntentServiceRegistration.ExecutionLocality.ValueType  # 1

    NAME_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    URL_FIELD_NUMBER: builtins.int
    LOCALITY_FIELD_NUMBER: builtins.int
    name: typing.Text
    version: typing.Text
    url: typing.Text
    locality: global___IntentServiceRegistration.ExecutionLocality.ValueType
    def __init__(self,
        *,
        name: typing.Text = ...,
        version: typing.Text = ...,
        url: typing.Text = ...,
        locality: global___IntentServiceRegistration.ExecutionLocality.ValueType = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["locality",b"locality","name",b"name","url",b"url","version",b"version"]) -> None: ...
global___IntentServiceRegistration = IntentServiceRegistration

class AnnounceRequest(google.protobuf.message.Message):
    """*
    This is used as input to the `Announce` method.

    Message to check if a service is already registered and also to announce a
    service's health to Chariott.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SERVICE_FIELD_NUMBER: builtins.int
    @property
    def service(self) -> global___IntentServiceRegistration: ...
    def __init__(self,
        *,
        service: typing.Optional[global___IntentServiceRegistration] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["service",b"service"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["service",b"service"]) -> None: ...
global___AnnounceRequest = AnnounceRequest

class AnnounceResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    REGISTRATION_STATE_FIELD_NUMBER: builtins.int
    registration_state: global___RegistrationState.ValueType
    def __init__(self,
        *,
        registration_state: global___RegistrationState.ValueType = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["registration_state",b"registration_state"]) -> None: ...
global___AnnounceResponse = AnnounceResponse

class RegisterRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SERVICE_FIELD_NUMBER: builtins.int
    INTENTS_FIELD_NUMBER: builtins.int
    @property
    def service(self) -> global___IntentServiceRegistration: ...
    @property
    def intents(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___IntentRegistration]: ...
    def __init__(self,
        *,
        service: typing.Optional[global___IntentServiceRegistration] = ...,
        intents: typing.Optional[typing.Iterable[global___IntentRegistration]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["service",b"service"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["intents",b"intents","service",b"service"]) -> None: ...
global___RegisterRequest = RegisterRequest

class RegisterResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___RegisterResponse = RegisterResponse

class IntentRegistration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _Intent:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _IntentEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[IntentRegistration._Intent.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        INTENT_DISCOVER: IntentRegistration._Intent.ValueType  # 0
        INTENT_INSPECT: IntentRegistration._Intent.ValueType  # 1
        INTENT_READ: IntentRegistration._Intent.ValueType  # 2
        INTENT_WRITE: IntentRegistration._Intent.ValueType  # 3
        INTENT_INVOKE: IntentRegistration._Intent.ValueType  # 4
        INTENT_SUBSCRIBE: IntentRegistration._Intent.ValueType  # 5
    class Intent(_Intent, metaclass=_IntentEnumTypeWrapper):
        pass

    INTENT_DISCOVER: IntentRegistration.Intent.ValueType  # 0
    INTENT_INSPECT: IntentRegistration.Intent.ValueType  # 1
    INTENT_READ: IntentRegistration.Intent.ValueType  # 2
    INTENT_WRITE: IntentRegistration.Intent.ValueType  # 3
    INTENT_INVOKE: IntentRegistration.Intent.ValueType  # 4
    INTENT_SUBSCRIBE: IntentRegistration.Intent.ValueType  # 5

    NAMESPACE_FIELD_NUMBER: builtins.int
    INTENT_FIELD_NUMBER: builtins.int
    namespace: typing.Text
    intent: global___IntentRegistration.Intent.ValueType
    def __init__(self,
        *,
        namespace: typing.Text = ...,
        intent: global___IntentRegistration.Intent.ValueType = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["intent",b"intent","namespace",b"namespace"]) -> None: ...
global___IntentRegistration = IntentRegistration

class FulfillRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAMESPACE_FIELD_NUMBER: builtins.int
    INTENT_FIELD_NUMBER: builtins.int
    namespace: typing.Text
    @property
    def intent(self) -> chariott.common.v1.common_pb2.Intent: ...
    def __init__(self,
        *,
        namespace: typing.Text = ...,
        intent: typing.Optional[chariott.common.v1.common_pb2.Intent] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["intent",b"intent"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["intent",b"intent","namespace",b"namespace"]) -> None: ...
global___FulfillRequest = FulfillRequest

class FulfillResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FULFILLMENT_FIELD_NUMBER: builtins.int
    @property
    def fulfillment(self) -> chariott.common.v1.common_pb2.Fulfillment: ...
    def __init__(self,
        *,
        fulfillment: typing.Optional[chariott.common.v1.common_pb2.Fulfillment] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["fulfillment",b"fulfillment"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["fulfillment",b"fulfillment"]) -> None: ...
global___FulfillResponse = FulfillResponse
