# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from sdv.proto.chariott.streaming.v1 import streaming_pb2 as chariott_dot_streaming_dot_v1_dot_streaming__pb2


class ChannelServiceStub(object):
    """*
    The streaming service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Open = channel.unary_stream(
                '/chariott.streaming.v1.ChannelService/Open',
                request_serializer=chariott_dot_streaming_dot_v1_dot_streaming__pb2.OpenRequest.SerializeToString,
                response_deserializer=chariott_dot_streaming_dot_v1_dot_streaming__pb2.Event.FromString,
                )


class ChannelServiceServicer(object):
    """*
    The streaming service definition.
    """

    def Open(self, request, context):
        """*
        Open a new channel to the provider.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChannelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Open': grpc.unary_stream_rpc_method_handler(
                    servicer.Open,
                    request_deserializer=chariott_dot_streaming_dot_v1_dot_streaming__pb2.OpenRequest.FromString,
                    response_serializer=chariott_dot_streaming_dot_v1_dot_streaming__pb2.Event.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chariott.streaming.v1.ChannelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChannelService(object):
    """*
    The streaming service definition.
    """

    @staticmethod
    def Open(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/chariott.streaming.v1.ChannelService/Open',
            chariott_dot_streaming_dot_v1_dot_streaming__pb2.OpenRequest.SerializeToString,
            chariott_dot_streaming_dot_v1_dot_streaming__pb2.Event.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
