# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chariott/streaming/v1/streaming.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sdv.proto.chariott.common.v1 import common_pb2 as chariott_dot_common_dot_v1_dot_common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%chariott/streaming/v1/streaming.proto\x12\x15\x63hariott.streaming.v1\x1a\x1f\x63hariott/common/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\r\n\x0bOpenRequest\"}\n\x05\x45vent\x12\x0e\n\x06source\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.chariott.common.v1.Value\x12\x0b\n\x03seq\x18\x03 \x01(\x04\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2^\n\x0e\x43hannelService\x12L\n\x04Open\x12\".chariott.streaming.v1.OpenRequest\x1a\x1c.chariott.streaming.v1.Event\"\x00\x30\x01\x62\x06proto3')



_OPENREQUEST = DESCRIPTOR.message_types_by_name['OpenRequest']
_EVENT = DESCRIPTOR.message_types_by_name['Event']
OpenRequest = _reflection.GeneratedProtocolMessageType('OpenRequest', (_message.Message,), {
  'DESCRIPTOR' : _OPENREQUEST,
  '__module__' : 'chariott.streaming.v1.streaming_pb2'
  # @@protoc_insertion_point(class_scope:chariott.streaming.v1.OpenRequest)
  })
_sym_db.RegisterMessage(OpenRequest)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'chariott.streaming.v1.streaming_pb2'
  # @@protoc_insertion_point(class_scope:chariott.streaming.v1.Event)
  })
_sym_db.RegisterMessage(Event)

_CHANNELSERVICE = DESCRIPTOR.services_by_name['ChannelService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OPENREQUEST._serialized_start=130
  _OPENREQUEST._serialized_end=143
  _EVENT._serialized_start=145
  _EVENT._serialized_end=270
  _CHANNELSERVICE._serialized_start=272
  _CHANNELSERVICE._serialized_end=366
# @@protoc_insertion_point(module_scope)
